### PR TITLE
builtin/app/php: build & deploy

### PR DESCRIPTION
**Pull request by phinze**

### CODE REVIEW

**Comment by lyrixx** [comment]
Hello.

I would like to understand your choices here.

On your website, you said:

> Otto automatically builds an infrastructure and deploys your application using industry standard tooling and best practices, so you don't have to.

But I can see you made very opinionated choices that I don't understand. 

For example:

* you are using Apache2, where almost everyone is using nginx 
* you are installing `php5-fpm`, but you don't use it as you are using `mod_php` (in apache2).
* you install `php5-mysql` and `php5-pgsql` ; usually, you are using one or another one DB. not both at the same time
* the default directory for `.php` is usually `/var/www` and not `/srv/otto-app`
* the directory exposed by apache is the same as the one where the code is deployed. This is a bad pratice, because it exposes all .php. Nowadays, we have front controller. For exemple all your code lives in /var/www but nginx/apache2 only expose /var/www/web. And this folder only contains one `.php` file: `index.php`

I have more to day on the default installation, If you need more informations, feel free to ping me ;)

**Comment by phinze** [comment]
@lyrixx this is great feedback - and precisely the sort of detail Otto needs to get smarter!

I'll fan out a few issues from what you've said here and link them back to this thread, and please feel free to add more or elaborate on the ones I open. :+1:

**Comment by phinze** [comment]
Okay I picked up what I saw as the two most important issues you mentioned. For the rest:

 * php5-fpm - will be necessary if we switch to nginx. did a bit more reading and it sounds like fpm is "the future" anyways yes?
 * mysql/pgsql - seems like it might be easiest to just install both, unless there is a consistent way of detecting which is used? feel free to open an issue if you have ideas.
 * default directory - feels relatively cosmetic to me, but happy to discuss it in an issue if you feel it's important

Thanks again for all the information! Looking forward to working this into Otto. :grinning:

**Comment by lyrixx** [comment]
> default directory - feels relatively cosmetic to me, but happy to discuss it in an issue if you feel it's important

yes, indeed ;)

> php5-fpm - will be necessary if we switch to nginx. did a bit more reading and it sounds like fpm is "the future" anyways yes?

For us (a SensioLabs / Blackfire, the company behing Symfony Framework) YES.

> mysql/pgsql - seems like it might be easiest to just install both, unless there is a consistent way of detecting which is used? feel free to open an issue if you have ideas.

There is no consistent way ...

As you can see, it's hard to detect everything on a PHP application.
In a perfect world, users should update  their `composer.json` with strict requirements event for platform.

This is why I fail to see how otto can configure everything auto-magically.

**Pull request merged**
