### PR TITLE
Add Java based project support

### LINKED ISSUE #80: Support Maven based projects
A pom file should give you plenty of info to set up an environment. Use it wisely!

### LINKED ISSUE #275: Support Gradle based projects
A `build.gradle` file should give enough information to set up an environment.

### PR DESCRIPTION
**Pull request by pcssi**
Gets a basic Java environment stood up with Gradle and Maven installed for dependency management and build systems. Still needs a lot of polish.

Hopefully this pull request will provide more eyes on the code to help clean it up.

* Closes #275 
* Closes #80 

[edited to reflect changes after thinking about @justincampbell's [comment](https://github.com/hashicorp/otto/pull/276#issuecomment-161035707).]

### CODE REVIEW

**Comment by justincampbell** [comment]
Is Gradle itself a language/framework that we'd want to support by name? Or should this be a "Java" or "Groovy" apptype, with the best practice being to use Gradle as the preferred build system?

**Comment by pcssi** [comment]
"Java" apptype with different build systems is my vote. #80 can be addressed via this approach as well. 

Do you have any other apptypes with different build systems which otto changes as it finds different configuration files?

**Comment by pcssi** [comment]
#285 also falls under this apptype. [`sbt`](http://www.scala-sbt.org/) could take the place of Gradle or Maven in that scenario.

**Comment by mitchellh** [comment]
This looks really good. Great job to keep this up to date. I'm going to make some changes to extract the remote logic into a ScriptPack (new thing) but the rest looks really good. Hopefully you can keep making improvements once it is in :)

**Comment by twashing** [comment]
Can we add [Clojure](http://clojure.org/) apptype support to this list? The 2 major build tools in this space are [leinigen](http://leiningen.org/) and [boot](http://boot-clj.com/).

**Comment by malchmih** [comment]
+1 for Clojure. Would be great!

**Comment by pcssi** [comment]
Yes. I looked into it, and adding those two build tools to the Vagrant box's provisioning step does not seem to be that difficult. Once provisioned it is as simple as detecting `project.clj` or `build.boot`.

**Pull request merged**
