### PR TITLE
Add support for Parallels

### PR DESCRIPTION
**Pull request by rickard-von-essen**
Use Parallels Ubuntu 12.04 box for Vagrant Parallels provider.

### CODE REVIEW

**Comment by legal90** [comment]
@rickard-von-essen :+1: 

By the way, do we have to use ubuntu-12.04 exactly? There is `parallels/ubuntu-14.04` box as well

**Comment by patrys** [comment]
14.04 is the current LTS so it looks like a better candidate.

**Comment by rickard-von-essen** [comment]
I took the same as for VirtualBox / VMware. I think it is a separation issue to switch all to 14.04, but that requires some testing to verify all provisioning works as expected.

**Comment by sethvargo** [comment]
Let's use 12.04 for now and we can upgrade to 14.04 across all the boxes in one PR in the future :smile:

**Comment by phinze** [comment]
LGTM - agreed that we'll sweep an update to 14.04 very soon.

**Pull request merged**
