### PR TITLE
Add python 3.4 / 3.5 to install.sh

### LINKED ISSUE #429: Error "Unknown Python version: 3.5" when running `otto dev`
Is Python 3.5 not supported? I couldn't find any documentation that listed any versions. Here is my simple Appfile with the errors in the comments https://gist.github.com/qmcree/e69b18f7ed69743d9c9f

### PR DESCRIPTION
**Pull request by maxnordlund**
This should fix #429 and enable people to use the newer versions of python (which have been out of quite some time now).

### CODE REVIEW

**Comment by qmcree** [comment]
Thank you, @maxnordlund!

**Comment by maxnordlund** [comment]
No problem, just wished that the CI tests included bats as well (or am I missing something?)

**Comment by stevenpollack** [comment]
Man, I wish this would get merged in... Thanks, @maxnordlund !! :+1:

**Comment by Castillosa** [comment]
@stevenpollack  +1, Someone knows what happens?

**Comment by qmcree** [comment]
+1

**Comment by maxnordlund** [comment]
Yeah, what gives? But seriously, this would help a lot of people, and seems to cause no additional problems, so would @derekpeterson or @garrypolley mind looking at this?

Pretty please.

**Comment by derekpeterson** [comment]
@maxnordlund I think you had a different Derek Peterson in mind.

**Comment by maxnordlund** [comment]
Darn it, sorry for the ping then.

**Comment by Castillosa** [comment]
:+1: maybe, @mitchellh

**Comment by bjornpost** [comment]
+1

**Comment by minhoryang** [comment]
+1 According to [c19d41af601556658f6b054b32ddf0f24ae7082f](https://github.com/hashicorp/otto/blob/c19d41af601556658f6b054b32ddf0f24ae7082f/website/source/docs/apps/python/customization.html.md), we can get 3.4!! but...

**Comment by 007lva** [comment]
:+1:

**Comment by armon** [comment]
Thank you for your contribution. Sadly, we have [decommissioned Otto](https://www.hashicorp.com/blog/decommissioning-otto.html), and are no longer developing or supporting the project.

**Pull request closed without merging**
