### PR TITLE
Fix hashicorp/otto#391

### LINKED ISSUE #391: Vagrant file provisioning fails on Windows
An initial `otto dev` executed on a Windows host fails after the box was added:

```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

File provisioner:
* File upload source file C:/Users/mbrodala/.otto.d/global-data/vagrant-layered/layers/consul/UsersmbrodalaDesktop
              ail.ottompiledpp criptpacksSTDLIB.tar.gz must exist
* File upload source file C:/Users/mbrodala/.otto.d/global-data/vagrant-layered/layers/consul/UsersmbrodalaDesktop
              ail.ottompiledpp criptpacksPHP.tar.gz must exist


Error building dev environment: Error building dev environment layers: Error executing Vagrant: exit status 1

The error messages from Vagrant are usually very informative.
Please read it carefully and fix any issues it mentions. If
the message isn't clear, please report this to the Otto project.
```

(The project directory was replaced with `fail` for this report but the original one also starts with an `f`.)

Inspecting the `Vagranfile` at the mentioned location indeed shows the error:

```ruby
# Generated by Otto, do not edit!
#
# This is a Vagrantfile that represents a single layer of a multi-layered
# dev environment. Do not modify, boot, or destroy this environment since
# it can corrupt other environments very easily.

Vagrant.configure("2") do |config|

  if ENV["OTTO_VAGRANT_LAYER_PATH"]
    config.vm.clone = ENV["OTTO_VAGRANT_LAYER_PATH"]
  else
    config.vm.box = "hashicorp/precise64"
    config.vm.box_check_update = false
    config.vm.provider :parallels do |p, o|
      o.vm.box = "parallels/ubuntu-12.04"
    end
  end


  # ScriptPacks
  dir = "/otto/scriptpacks"
  config.vm.provision "shell", inline: "sudo rm -rf #{dir}; sudo mkdir -p #{dir}; sudo chmod 0777 #{dir}"

  config.vm.provision "file", source: "C:\Users\mbrodala\Desktop\fail\.otto\compiled\app\scriptpacks\STDLIB.tar.gz", destination: "#{dir}/STDLIB.tar.gz"
  config.vm.provision "shell", inline: "cd #{dir}; sudo mkdir STDLIB; sudo tar xzf STDLIB.tar.gz -C STDLIB"

  config.vm.provision "file", source: "C:\Users\mbrodala\Desktop\fail\.otto\compiled\app\scriptpacks\PHP.tar.gz", destination: "#{dir}/PHP.tar.gz"
  config.vm.provision "shell", inline: "cd #{dir}; sudo mkdir PHP; sudo tar xzf PHP.tar.gz -C PHP"


  # Use a linked clone if we can
  config.vm.provider "virtualbox" do |v|
    v.linked_clone = true
  end

  if Vagrant.has_plugin?("vagrant-parallels", ">= 1.6.0")
    config.vm.provider "parallels" do |p|
      p.linked_clone = true
    end
  end

  # Disable the default synced folder
  config.vm.synced_folder ".", "/vagrant", disabled: true


  dir = "/otto/foundation-layer-consul"
  config.vm.synced_folder 'C:\Users\mbrodala\Desktop\faz-jobs-distribution\.otto\compiled\app\foundation-consul\app-dev', dir
  config.vm.provision "shell", inline: "cd #{dir} && bash #{dir}/layer.sh"

end
```

As you can see the backslashes of the file provisioner sources are neither escaped nor within single quotes. Thus they are evaluated as escape sequences as seen by `\f` triggering a line feed and `\c` trying to output a unicode character.

Since there are no variables in these strings, simple enclosing them with single quotes should do the trick.

### PR DESCRIPTION
**Pull request by castaneai**
Fix #391

### CODE REVIEW

**Comment by jkxyz** [comment]
:+1: Thanks for the fix. ETA on this getting merged?

**Comment by SanderKnape** [comment]
Also running into this issue. Would be great if this would get fixed!

**Comment by stkerr** [comment]
Also having this issue, please merge.

**Comment by thiagotalma** [comment]
Hello!
@armon @catsby @clstokes @jefferai @justincampbell @markupboy @meirish @mitchellh @pearkes @phinze @ryanuber @sethvargo 

Is anybody there?
This is an error that make it impossible the otto be used in WIndows.
The solution is standing here for 28 days...

**Comment by armon** [comment]
Our apologies! Lots of things happening in parallel at HC

**Comment by thiagotalma** [comment]
Thanks, @armon!

**Comment by danday74** [comment]
Waiting for this Windows fix!

**Comment by Conceede** [comment]
Hi,

I'm sorry to reopen this subject but i'm trying to install otto v0.2 on Windows. I followed every steps of the tutorial and read all your posts, but I don't know what to do to avoid this error. Even when I'm fixing my Vagrantfiles, otto rewrite on them during the dev steps and this error appears after it. 
I don't get how to fix it, if someone can help, it would be just perfect =) .

Thanks =)

**Comment by dilev01** [comment]
+1

**Comment by stkerr** [comment]
I believe this is still an issue since v0.2 was released in January, but this was merged into head afterwards. To fix it, you must either build from source locally or wait for Hashicorp to put a new version out on the release page.

**Pull request merged**
