### PR TITLE
vendor go dependencies using govendor

### PR DESCRIPTION
**Pull request by devoid**
Hiya, this commit tries to follow the patterns in other Hashicorp projects for vendoring Go dependencies. Let me know what you think!

- Use github.com/kardianos/govendor tool to vendor dependencies as
  pulled in via the 'updatedeps' make target on 2016-06-20.

- Note that this currently fails testing due to a type error with
  ./helper/terraform/outputs.go:L22. After doing at git blame I was
  not able to identify a working terraform version. A blame against
  terraform on the state.RootModule().Outputs attribute points to [1].

- Note: this change requires go1.6 or greater. To support go1.5 I can
  add GO15VENDOREXPERIMENT environment settings to the build targets.

[1] https://github.com/hashicorp/terraform/commit/3ea3c657b5d0a5974517756c2ee41fb4998647b2

### CODE REVIEW

**Comment by devoid** [comment]
* See the [Go:tip](https://travis-ci.org/hashicorp/otto/jobs/139114611) build for an example of the bug I can't figure out.
* If you're content with the approach, let me know and I can start working on the go1.5 environment variable work to get [Go:1.5 tests](https://travis-ci.org/hashicorp/otto/jobs/139114610) passing.

**Comment by leowmjw** [comment]
@devoid Check out #510 for signature of all the needed deps for v0.2.  The list likely is a little too broad (it has some remnants from govendor deps).

The problematic deps are usually terraform, hcl, hil:
```
/Users/leow/GOLANGPROJ/GOPATH_OTTO_v0.2/src/github.com/hashicorp/hcl
commit e96d23138c76470c808bf6586bdaf981bbd25cae
/Users/leow/GOLANGPROJ/GOPATH_OTTO_v0.2/src/github.com/hashicorp/hil
commit 0ab0eeb5d6a47777dd82249b4de4d19f41674401
/Users/leow/GOLANGPROJ/GOPATH_OTTO_v0.2/src/github.com/hashicorp/terraform
commit 862c5d958fa6d1427ce0e0ad429b14e0f6c87414
```

**Comment by devoid** [comment]
@leowmjw I tried grabbing all of those dependency versions (including the other ones mentioned in the file). This resulted in a compile-failure due to a type error in the hashicorp/hil package. I can push up the WIP on that but I think the best way forward is to get terraform and other components working. My most recent commit tries to do that.

**Comment by leowmjw** [comment]
@devoid , i am not very familiar on how govendor works but I presume the master branch must be at that version. My copy, I must not update via git pull (no make updatedeps). I basically had to copy the dependencies that is working

**Comment by devoid** [comment]
@leowmjw govendor pulls packages into the ./vendor directory from the GOPATH and records the rcs (git, hg, svn) checksum that it used when pulling sources in. So the trick here is getting the right versions of dependencies (via updatedeps) into the GOPATH before running the govendor commands. As you note here and in #510 terraform changed an API that causes otto's helper/terraform package to break. So here I just fix the otto package.

**Comment by armon** [comment]
Thank you for your contribution. Sadly, we have [decommissioned Otto](https://www.hashicorp.com/blog/decommissioning-otto.html), and are no longer developing or supporting the project.

**Pull request closed without merging**
