### PR TITLE
Init of DO Infrastructure

### PR DESCRIPTION
**Pull request by bscott**
Starting working on the base for supporting a simple flavor of
DigitalOcean Infra.

### CODE REVIEW

**Comment by maveonair** [comment]
:+1:

**Comment by ekryski** [comment]
Oh hells yeah! Sweet!

**Comment by mitchellh** [comment]
Hey @bscott, thanks! We're making a huge push for production-grade deploys in 0.3 (as opposed to demo-quality deploys in current Otto). This is going to require a bit of a rearchitecture of the infra stuff so I've been holding off. I'll take a look at this again in a bit, but it'll miss 0.2, sorry!

**Comment by ekryski** [comment]
@mitchellh Do you guys have a rough idea when you'd like to see 0.3 come out? I'm itching to have Digital Ocean integration here. Currently just using custom Terraform stuff to do it all.

**Comment by mitchellh** [comment]
@ekryski We don't have any strong timelines yet since a lot of it is actually still in the design (pre-code) phase.

**Comment by mitchellh** [comment]
Personally I'm hoping in a couple months.

**Comment by ekryski** [comment]
@mitchellh Totally get it. That sound good, thanks. I'm definitely more on the Developer side of the DevOps equation but willing to help out any way I can.

**Comment by bhurlow** [comment]
:+1: @mitchellh sounds good!

**Comment by enxebre** [comment]
related to https://github.com/hashicorp/otto/pull/183

**Comment by bscott** [comment]
@mitchellh Np, Thanks for the update!

**Comment by ssteinerx** [comment]
I'm really needing DO support.  Can I just kind of squeeze this in somewhere and see if it works?  Any ideas appreciated...

**Comment by jkirkby91** [comment]
@ssteinerx why not just check out the branch?

But yes looking forward to official merge of this!!!

**Comment by edbizarro** [comment]
+1

**Comment by jkirkby91** [comment]
+1 on this!!!!! great news

**Comment by abraunton** [comment]
+1 this is exciting!

**Comment by ssteinerx** [comment]
Is there anything that has to be done before this is merged?

**Comment by benrogmans** [comment]
Let's go!?

**Comment by armon** [comment]
Thank you for your contribution. Sadly, we have [decommissioned Otto](https://www.hashicorp.com/blog/decommissioning-otto.html), and are no longer developing or supporting the project.

**Pull request closed without merging**
