### PR TITLE
Add automatic apt dectection for pip packages

### LINKED ISSUE #400: Python base image should include libmysqlclient-dev
I have a Python app with a dependency: `mysqlclient==1.3.6`. When I `otto dev ssh` into my VM, and run `pip install -r requirements.txt`, I get this error:

```
Collecting mysqlclient==1.3.6 (from -r requirements.txt (line 35))
  Using cached mysqlclient-1.3.6.tar.gz
    Complete output from command python setup.py egg_info:
    sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-EIKUK9/mysqlclient/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 47, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found
```

Since MySQL is commonly used with Python apps, I suggest that `libmysqlclient-dev` be included in the base image for the Python app type.

If I am wrong, is there another solution I should be using? I have looked through the docs and I'm not finding a hook for me to specify that Otto run a command like "apt-get install".

### PR DESCRIPTION
**Pull request by maxnordlund**
This is equivalent of the Ruby gem detection logic. It only adds PostgreSQL, but the boilerplate is there for people to add other dependencies, like NumPy/SciPy/Pillow etc.

This kinda closes #400, but the specifics for MySQL needs to be added.

### CODE REVIEW

**Comment by leowmjw** [comment]
@maxnordlund Your patch did not seem to work for me.  It seems to be only installed outside of the virtualenv.  Shouldn't the pip install be done inside virtualenv instead?

**Comment by leowmjw** [comment]
This worked for me:
```
leow$ git diff
diff --git a/builtin/app/python/data/common/dev/Vagrantfile.tpl b/builtin/app/python/da
index 7847d72..08cb812 100644
--- a/builtin/app/python/data/common/dev/Vagrantfile.tpl
+++ b/builtin/app/python/data/common/dev/Vagrantfile.tpl
@@ -23,11 +23,14 @@ oe git config --global url."git@github.com:".insteadOf "https://git
 # Make it so that `vagrant ssh` goes directly to the correct dir
 vagrant_default_cd "vagrant" "/vagrant"
 
-# Go to our working directory and install gems
+# Go to our working directory and install pip packages
 cd /vagrant
 
 if [ -f requirements.txt ]; then
-  python_pip_apt
+  # Activate environment
+  otto_output "Activating VirtualEnv..."
+  . /home/vagrant/virtualenv/bin/activate
+  pip install --upgrade pip
   otto_output "Installing pip packages..."
   pip install -r requirements.txt
 fi
```

**Comment by maxnordlund** [comment]
Yeah, I assumed I already was in an virtualenv environment, but guess not. I'll merge that into this. Thanks for spotting it.

**Comment by wldhx** [comment]
@maxnordlund It seems you've [removed](https://github.com/hashicorp/otto/pull/431/commits/d68f7833f7784597e9c81fac8966ab4ed77ae8be#diff-cad54b34b1a8ff606662038d5f51bca9L30) the actual call of `python_pip_apt` by merging d68f783.

**Comment by wldhx** [comment]
Also, this only works for local dev env, not for deployment artifacts, right?

**Comment by maxnordlund** [comment]
Yeah, I guess it did disappear. It should work in dev and production, but I didn't test that. This is a first pass though, and it seems like this project is not doing to hot. It has barely had any commits lately. I hope they merge this though.

**Comment by wldhx** [comment]
As far as I understand, Vagrant is not used for infra; scripts in `builtin/app/python/data/$INFRA_TYPE` are. Therefore, this PR should only work for dev env.
Will have to retest though.

I'm also somewhat concerned about otto in general - hope they'll be done with quite a major overhaul they've been planning in `0.3` and it'll get better.

**Comment by armon** [comment]
Thank you for your contribution. Sadly, we have [decommissioned Otto](https://www.hashicorp.com/blog/decommissioning-otto.html), and are no longer developing or supporting the project.

**Pull request closed without merging**
