### PR TITLE
Indicate which versions of windows are supported

### PR DESCRIPTION
**Pull request by johnyesberg**

### CODE REVIEW

**Comment by johnyesberg** [comment]
Thanks for your work on Otto. I spent some time trying to get it working on Windows 7 before discovering that Windows 7 doesn't have Hyper-V, and so can't run the vagrant box the way Otto wants. It was frustrating to discover that I had wasted my time, and I wanted to see if I could help others avoid such frustration.

**Comment by phinze** [comment]
Hi @johnyesberg - thanks for the report and sorry for the trouble getting up and running with Otto!

I'm surprised that Windows 7 would have trouble, though, since we lean on Vagrant for dev environments, and I'm fairly certain that Vagrant is fully supported on Win7.

Can you share the error message you got when trying to use Otto?

**Comment by johnyesberg** [comment]
Hi @phinze 
See the output below. Vagrant certainly can work on Windows 7 using, say, Virtualbox. But I understand that the Hyper-V provider won't work on Windows 7 (http://superuser.com/questions/29575/does-windows-7-support-hyper-v). However, given your surprise, I'll explore further. I've just noticed this guide which might help http://blogs.technet.com/b/schadinio/archive/2010/07/09/installing-hyper-v-manager-on-windows-7.aspx.

Can you tell me whether Otto relies on any aspects of the Hyper-V provider, or do you think it might work with another provider like Virtualbox?

John

```
C:\...\otto-getting-started>otto dev                                  
==> Creating local development environment with Vagrant if it doesn't exist...                   
    Raw Vagrant output will begin streaming in below. Otto does                                  
    not create this output. It is mirrored directly from Vagrant                                 
    while the development environment is being created.                                          
                                                                                                 
Bringing machine 'default' up with 'hyperv' provider...                                          
==> default: Verifying Hyper-V is enabled...                                                     
==> default: Importing a Hyper-V instance                                                        
There are no virtual switches created for Hyper-V! Please open                                   
the Hyper-V Manager, go to the "Virtual Switch Manager", and create                              
at least one virtual switch.                                                                     
                                                                                                 
A virtual switch is required for Vagrant to create a Hyper-V                                     
machine that is connected to a network so it can access it.                                      
                                                                                                 
For more help, please see the documentation on the Vagrant website                               
for Hyper-V.                                                                                     
                                                                                                 
Error building dev environment: Error executing Vagrant: exit status 1                           
                                                                                                 
The error messages from Vagrant are usually very informative.                                    
Please read it carefully and fix any issues it mentions. If                                      
the message isn't clear, please report this to the Otto project.                                 
                                                                                                 
C:\Users\...\otto-getting-started>                                          
                                                                                                 
```

**Comment by johnyesberg** [comment]
Even though I have successfully installed the Hyper-V *Manager* on Windows 7 as per the link above, I still don't think I can install Hyper-V itself. With the manager, I can "connect" to manage my local machine, but it says that "Hyper-V has not been installed on computer localhost".

**Comment by phinze** [comment]
> Can you tell me whether Otto relies on any aspects of the Hyper-V provider, or do you think it might work with another provider like Virtualbox?

This is definitely weird! I can tell you that Otto doesn't rely in Hyper-V at all. We're using it with VirtualBox and VMware providers on our side.

**Comment by johnyesberg** [comment]
Trying again at home. Perhaps if vagrant doesn't find VirtualBox on the path, it will choose Hyper-V as the default provider. I started by setting environment variable VAGRANT_DEFAULT_PROVIDER=virtualbox and vagrant gave me an error indicating that it couldn't find VBoxManage.exe, and that it needs to be on the path. When I fixed that (and started a new cmd.exe shell with no VAGRANT_DEFAULT_PROVIDER set), ```otto dev``` started vagrant loading precise64 for virtualbox. So that seems successful so far. 

I recommend rejecting this pull request.

**Pull request closed without merging**
